### ISSUE TITLE
Why is there a constraint for numpy version in setup.py?

### ISSUE THREAD

**Issue by quantumdot** [helpmefindaname/BrownClustering#1]
Hi, thanks for the great library! I am running into some dependency conflicts when trying to use this package in my code. Your `setup.py` file specifies `numpy<1.21`, but many of my other dependencies ask for `numpy>=1.21`. Just wondering if your version constraint is truly necessary? Is it possible to remove the constraint?

**Comment by helpmefindaname** [comment]
Hi @quantumdot,
sorry for the late response, you are right: `numpy<1.21` is not really required. I remember that I had some troubles when I created the lib back them, however that is nothing I can reproduce and I assume it was because of a specific (by now outdated) version of numba.

You can check out the new release `0.1.6` to use newer numpy versions
